import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#7c3aed',
  code: 'EC',
  label: 'E-Commerce & Retail',
  canonical: '/industries/ecommerce',
  metaTitle: 'E-Commerce & Retail | LogicWorks — Platform Builds & CRO',
  metaDescription: 'LogicWorks delivers end-to-end e-commerce excellence — Shopify, WooCommerce, and custom platform builds with SEO, paid ads, and CRO that drives revenue.',
  heroTitle: <>E-Commerce &<br /><span>Retail</span></>,
  heroSub: 'End-to-end e-commerce excellence — platform builds, SEO, paid ads, and CRO that transform browsers into buyers and one-time purchasers into loyal customers.',
  ctaBtn: 'Get an E-Commerce Audit',
  ctaNote: 'FREE STORE AUDIT · REVENUE ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for E-Commerce',
  ctaTitle: <>TRAFFIC IS VANITY.<br /><em>REVENUE IS SANITY</em>.</>,
  ctaSub: 'Book a free e-commerce audit and uncover the conversion leaks costing you revenue every day.',
  metrics: [
    { val: '47%', lbl: 'Average Revenue Lift' },
    { val: '3.8%', lbl: 'Conversion Rate Achieved' },
    { val: '2.4x', lbl: 'ROAS on Paid Media' },
    { val: '$0', lbl: 'Lost to Cart Abandonment' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>97% VISIT.<br /><em>3% BUY</em></>,
  challengeDesc: 'The average e-commerce conversion rate sits at 2–3%. Most stores bleed revenue through slow load times, poor mobile UX, weak product pages, and cart abandonment flows that never recover lost sales. Every 0.1% conversion improvement is pure profit.',
  checks: ['Platform builds on Shopify, WooCommerce, and custom stacks', 'Conversion rate optimization across the full funnel', 'Shopping ads, feed optimization, and retargeting', 'Email automation for cart recovery and lifecycle marketing'],
  tags: ['Shopify', 'CRO', 'Google Shopping', 'Klaviyo', 'Amazon'],
  outcomes: [
    { icon: '💰', title: '47% Revenue Lift', desc: 'CRO and UX improvements that compound across every traffic source.' },
    { icon: '🛒', title: '3.8% Conversion Rate', desc: 'Optimized product pages, checkout, and mobile experience.' },
    { icon: '📈', title: '2.4x ROAS', desc: 'Shopping campaigns and retargeting with obsessive feed optimization.' },
    { icon: '📧', title: 'Cart Recovery Revenue', desc: 'Automated flows that recover 15–25% of abandoned carts.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>E-COMMERCE<br /><em>GROWTH ENGINE</em></>,
  solutionsDesc: 'Six capabilities that drive measurable revenue across every stage of the purchase funnel.',
  solutions: [
    { num: '01', title: 'Platform Development', desc: 'Shopify Plus, WooCommerce, and headless commerce builds with custom features, integrations, and scalable architecture.' },
    { num: '02', title: 'Conversion Rate Optimization', desc: 'A/B testing, heatmap analysis, checkout optimization, and UX improvements that systematically increase purchase rate.' },
    { num: '03', title: 'Product Page Excellence', desc: 'High-converting product templates with social proof, urgency, cross-sells, and SEO-optimized descriptions.' },
    { num: '04', title: 'Shopping Ads & Feed Optimization', desc: 'Google Shopping, Performance Max, and Meta catalog campaigns with feed optimization and bid management.' },
    { num: '05', title: 'Email & Lifecycle Marketing', desc: 'Klaviyo flows for welcome series, cart abandonment, post-purchase, and win-back campaigns.' },
    { num: '06', title: 'E-Commerce SEO', desc: 'Category architecture, product schema markup, and content strategy that drives organic product discovery.' },
  ],
  useCasesLabel: 'Store Types',
  useCasesTitle: <>RETAIL<br /><em>VERTICALS</em></>,
  useCasesDesc: 'E-commerce solutions across retail categories.',
  useCases: [
    { num: '01', title: 'DTC & Consumer Brands', desc: 'Brand-building stores with storytelling, subscription models, and community-driven growth.' },
    { num: '02', title: 'B2B & Wholesale', desc: 'Bulk ordering portals, tiered pricing, and account-based purchasing experiences.' },
    { num: '03', title: 'Marketplace & Multi-Vendor', desc: 'Multi-seller platforms with vendor dashboards, commission tracking, and unified checkout.' },
    { num: '04', title: 'Subscription & Recurring', desc: 'Recharge and subscription box builds with churn reduction and LTV optimization.' },
  ],
  processLabel: 'Process',
  processTitle: <>REVENUE IN<br /><em>5 PHASES</em></>,
  processDesc: 'From store audit to revenue optimization — structured e-commerce growth delivery.',
  timeline: [
    { num: '01', title: 'Store Audit', desc: 'Conversion funnel analysis, speed audit, competitive benchmarking, and revenue leak identification.' },
    { num: '02', title: 'Strategy & Roadmap', desc: 'Platform assessment, CRO priority matrix, and channel strategy for paid and organic growth.' },
    { num: '03', title: 'Build & Optimize', desc: 'Platform development or redesign, checkout optimization, and email flow deployment.' },
    { num: '04', title: 'Launch & Scale Ads', desc: 'Shopping feed setup, campaign launch, and retargeting audience activation.' },
    { num: '05', title: 'Optimize & Grow', desc: 'Continuous A/B testing, seasonal campaigns, and LTV optimization programs.' },
  ],
  stackLabel: 'Platforms',
  stackTitle: <>COMMERCE STACK<br /><em>MASTERED</em></>,
  stackDesc: 'E-commerce platforms, marketing tools, and integrations.',
  stack: ['Shopify Plus', 'WooCommerce', 'BigCommerce', 'Klaviyo', 'Google Shopping', 'Meta Catalog', 'Recharge', 'Stripe', 'ShipStation', 'Gorgias', 'Hotjar', 'Triple Whale'],
  faqTitle: <>E-Commerce<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What e-commerce leaders ask before investing in growth.',
  faqs: [
    { q: 'Shopify or custom build — which do you recommend?', a: 'Shopify Plus for most DTC brands scaling past $1M — fast, reliable, app ecosystem. Custom headless for unique UX requirements or B2B complexity. We recommend based on your catalog size, customization needs, and growth stage.' },
    { q: 'How much can CRO actually improve revenue?', a: 'Our average client sees 30–50% revenue lift from CRO alone — without increasing ad spend. Checkout optimization, product page improvements, and mobile UX fixes compound across all traffic sources.' },
    { q: 'Do you manage Google Shopping and Meta ads?', a: 'Yes. We manage full-funnel paid media — Google Shopping, Performance Max, Meta catalog ads, and retargeting — with feed optimization, bid management, and ROAS tracking.' },
    { q: 'Can you migrate our store without losing SEO?', a: 'We execute SEO-safe migrations with 301 redirect mapping, URL structure preservation, and post-migration monitoring to protect rankings during platform transitions.' },
    { q: 'How quickly can we launch a new store?', a: 'Shopify store with custom theme: 6–8 weeks. WooCommerce custom build: 8–12 weeks. Enterprise headless commerce: 4–6 months depending on integration complexity.' },
  ],
};

export default function Ecommerce() {
  return <IndustryInnerPage config={config} />;
}
