import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#2563eb',
  code: 'EDU',
  label: 'Education & EdTech',
  canonical: '/industries/education',
  metaTitle: 'Education & EdTech | LogicWorks — Enrollment Funnels & LMS',
  metaDescription: 'LogicWorks builds student enrollment funnels, LMS integrations, and digital marketing for schools, universities, and EdTech platforms.',
  heroTitle: <>Education &<br /><span>EdTech</span></>,
  heroSub: 'Student enrollment funnels, LMS integrations, and digital marketing for schools, universities, and EdTech platforms — turning interest into enrolled students and engaged learners.',
  ctaBtn: 'Get an Education Audit',
  ctaNote: 'FREE ENROLLMENT AUDIT · GROWTH ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for Education',
  ctaTitle: <>ENROLLMENT STARTS<br /><em>BEFORE THE FIRST VISIT</em>.</>,
  ctaSub: 'Book a free enrollment marketing audit and see how digital strategy fills your programs.',
  metrics: [
    { val: '64%', lbl: 'Enrollment Inquiry Lift' },
    { val: '2.9x', lbl: 'Application Completion' },
    { val: '45%', lbl: 'Cost Per Lead Reduction' },
    { val: '80+', lbl: 'Institutions Served' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>STUDENTS SHOP<br /><em>ONLINE FIRST</em></>,
  challengeDesc: 'Prospective students compare programs, read reviews, and evaluate institutions digitally before ever visiting campus. Schools with outdated websites, broken application flows, and zero digital marketing lose enrollment to competitors with modern, mobile-first experiences.',
  checks: ['Enrollment funnel optimization from inquiry to application', 'LMS and SIS integration for seamless student experience', 'Program-specific SEO and content marketing', 'Virtual tour and event marketing for remote prospects'],
  tags: ['Enrollment', 'LMS', 'EdTech', 'Student SEO', 'Virtual Events'],
  outcomes: [
    { icon: '🎓', title: '64% More Inquiries', desc: 'Program pages and SEO that capture student search intent.' },
    { icon: '📝', title: '2.9x Application Rate', desc: 'Streamlined application flows that reduce abandonment.' },
    { icon: '💰', title: '45% Lower CPL', desc: 'Organic enrollment marketing reduces paid dependence.' },
    { icon: '🌐', title: 'Global Reach', desc: 'Digital marketing that attracts international students.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>EDUCATION<br /><em>DIGITAL STACK</em></>,
  solutionsDesc: 'Six capabilities that drive enrollment and engagement across education sectors.',
  solutions: [
    { num: '01', title: 'Enrollment Funnel Design', desc: 'Multi-step inquiry forms, program finders, and nurture sequences that guide prospects from curiosity to application.' },
    { num: '02', title: 'Institutional Website Design', desc: 'Modern, accessible websites with program showcases, faculty profiles, virtual tours, and mobile-first application portals.' },
    { num: '03', title: 'Program-Specific SEO', desc: 'Degree and certificate landing pages optimized for student search queries and Google education features.' },
    { num: '04', title: 'EdTech Platform Development', desc: 'Learning management interfaces, student dashboards, and course marketplace builds for EdTech startups.' },
    { num: '05', title: 'Paid Enrollment Campaigns', desc: 'Google Ads, Meta, and YouTube campaigns targeting program-specific keywords and demographic segments.' },
    { num: '06', title: 'Analytics & Attribution', desc: 'Enrollment funnel tracking from first touch to matriculation with multi-channel attribution reporting.' },
  ],
  useCasesLabel: 'Institutions',
  useCasesTitle: <>EDUCATION<br /><em>SECTORS</em></>,
  useCasesDesc: 'Digital solutions across the education landscape.',
  useCases: [
    { num: '01', title: 'Universities & Colleges', desc: 'Undergraduate and graduate enrollment marketing with program-specific digital strategy.' },
    { num: '02', title: 'K-12 & Private Schools', desc: 'Parent-focused marketing, open house promotion, and community reputation building.' },
    { num: '03', title: 'EdTech & Online Learning', desc: 'Platform UX, course marketing, and growth strategies for digital education companies.' },
    { num: '04', title: 'Training & Certification', desc: 'Professional development program marketing and corporate training portal builds.' },
  ],
  processLabel: 'Process',
  processTitle: <>ENROLL IN<br /><em>5 PHASES</em></>,
  processDesc: 'From enrollment audit to student pipeline — structured education marketing delivery.',
  timeline: [
    { num: '01', title: 'Enrollment Audit', desc: 'Current funnel analysis, competitive benchmarking, and student journey mapping.' },
    { num: '02', title: 'Strategy & Content', desc: 'Program page architecture, SEO keyword strategy, and enrollment campaign planning.' },
    { num: '03', title: 'Build & Integrate', desc: 'Website development, LMS/SIS integration, and application flow optimization.' },
    { num: '04', title: 'Launch & Recruit', desc: 'SEO go-live, paid campaign activation, and virtual event marketing.' },
    { num: '05', title: 'Enroll & Optimize', desc: 'Ongoing CRO, seasonal campaigns, and yield optimization by program.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>EDTECH STACK<br /><em>CONNECTED</em></>,
  stackDesc: 'LMS, SIS, and enrollment marketing platforms.',
  stack: ['Canvas LMS', 'Blackboard', 'Moodle', 'Salesforce Education', 'Slate', 'HubSpot', 'Google Ads', 'Eventbrite', 'Zoom', 'Handshake', 'PowerSchool', 'Banner SIS'],
  faqTitle: <>Education<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What enrollment leaders ask before investing in digital student acquisition.',
  faqs: [
    { q: 'Can you integrate with our LMS and student information system?', a: 'Yes. We integrate with Canvas, Blackboard, Moodle, Banner, PowerSchool, and Slate for seamless data flow between marketing, admissions, and student records.' },
    { q: 'How do you market specific degree programs?', a: 'We build program-specific landing pages optimized for student search queries, create comparison content, and run targeted campaigns by program, demographic, and geographic market.' },
    { q: 'Do you work with EdTech startups or only institutions?', a: 'Both. We help EdTech companies with platform UX, course marketing, and growth strategy — as well as traditional institutions with enrollment marketing and website modernization.' },
    { q: 'How long is the enrollment marketing cycle?', a: 'Enrollment cycles vary by program. We typically begin campaigns 6–12 months before enrollment deadlines, with year-round SEO and nurture for rolling admissions programs.' },
    { q: 'Can you help attract international students?', a: 'Yes. Multi-language content, international SEO, geo-targeted campaigns, and virtual event marketing designed for global student recruitment.' },
  ],
};

export default function Education() {
  return <IndustryInnerPage config={config} />;
}
