import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#0d1b3e',
  code: 'FIN',
  label: 'Finance & FinTech',
  canonical: '/industries/finance',
  metaTitle: 'Finance & FinTech Solutions | LogicWorks — Compliant Digital',
  metaDescription: 'LogicWorks builds compliant, conversion-optimized digital experiences for banks, credit unions, RIAs, and FinTech startups with regulatory-aware design.',
  heroTitle: <>Finance &<br /><span>FinTech Solutions</span></>,
  heroSub: 'Compliant, conversion-optimized digital experiences for banks, credit unions, RIAs, and FinTech startups — where trust, security, and performance are non-negotiable.',
  ctaBtn: 'Get a Finance Audit',
  ctaNote: 'FREE COMPLIANCE READINESS AUDIT · GROWTH ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for Finance',
  ctaTitle: <>TRUST IS YOUR PRODUCT.<br /><em>YOUR DIGITAL SHOULD PROVE IT</em>.</>,
  ctaSub: 'Book a free compliance and conversion audit tailored to financial services regulations.',
  metrics: [
    { val: '52%', lbl: 'Conversion Rate Lift' },
    { val: 'SOC2', lbl: 'Security Standards' },
    { val: '2.8x', lbl: 'Lead Quality Score' },
    { val: '99.9%', lbl: 'Platform Uptime' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>COMPLIANCE AND<br /><em>CONVERSION COLLIDE</em></>,
  challengeDesc: 'Financial services face the hardest digital balancing act — regulatory compliance, consumer trust, and conversion optimization. Generic agencies create liability. You need a partner who understands FINRA, SEC, GDPR, and the psychology of financial decision-making.',
  checks: ['Regulatory-compliant copy and disclosure workflows', 'Bank-grade security and encryption standards', 'Conversion-optimized onboarding and application flows', 'Trust signals and social proof engineered for finance'],
  tags: ['FINRA', 'SOC 2', 'KYC/AML', 'FinTech', 'Wealth Management'],
  outcomes: [
    { icon: '📈', title: '52% Conversion Lift', desc: 'Optimized funnels that guide prospects through compliant application flows.' },
    { icon: '🔒', title: 'Regulatory Compliance', desc: 'FINRA, SEC, and GDPR-aware builds with audit trails.' },
    { icon: '🎯', title: '2.8x Lead Quality', desc: 'Targeting and qualification that surfaces high-intent prospects.' },
    { icon: '⚡', title: 'Enterprise Uptime', desc: '99.9% availability with financial-grade infrastructure.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>FINANCIAL DIGITAL<br /><em>EXCELLENCE</em></>,
  solutionsDesc: 'Six capabilities built for the unique demands of financial services marketing and technology.',
  solutions: [
    { num: '01', title: 'Compliant Website Development', desc: 'Regulatory-aware design with proper disclosures, accessibility compliance, and trust architecture that converts skeptical visitors.' },
    { num: '02', title: 'FinTech Product Design', desc: 'User onboarding flows, dashboard UX, and mobile app interfaces for banking, lending, and investment platforms.' },
    { num: '03', title: 'Lead Generation & Nurture', desc: 'Calculator tools, gated content, and email sequences that qualify prospects while maintaining compliance boundaries.' },
    { num: '04', title: 'Financial SEO & Content', desc: 'YMYL-optimized content, E-E-A-T signals, and keyword strategies for wealth management, lending, and insurance verticals.' },
    { num: '05', title: 'Secure Client Portals', desc: 'Encrypted client dashboards, document vaults, and account management portals with multi-factor authentication.' },
    { num: '06', title: 'Analytics & Attribution', desc: 'Compliant tracking, multi-touch attribution, and ROI dashboards mapped to financial services KPIs.' },
  ],
  useCasesLabel: 'Who We Serve',
  useCasesTitle: <>FINANCE<br /><em>SECTORS</em></>,
  useCasesDesc: 'Digital solutions across the financial services landscape.',
  useCases: [
    { num: '01', title: 'Banks & Credit Unions', desc: 'Member acquisition sites, online banking UX, and local branch SEO that drives deposits and loans.' },
    { num: '02', title: 'Wealth Management & RIAs', desc: 'Authority-building websites, client portals, and compliant content marketing for AUM growth.' },
    { num: '03', title: 'FinTech Startups', desc: 'Product-led growth sites, app store optimization, and investor-ready brand experiences.' },
    { num: '04', title: 'Insurance & Lending', desc: 'Quote funnels, comparison tools, and PPC campaigns with compliant landing pages.' },
  ],
  processLabel: 'Process',
  processTitle: <>COMPLIANT IN<br /><em>5 PHASES</em></>,
  processDesc: 'From regulatory audit to growth engine — structured financial services delivery.',
  timeline: [
    { num: '01', title: 'Compliance Review', desc: 'Regulatory landscape assessment, current asset audit, and competitive analysis.' },
    { num: '02', title: 'Strategy & UX', desc: 'Conversion funnel design, compliance workflow mapping, and trust architecture planning.' },
    { num: '03', title: 'Build & Secure', desc: 'Development with encryption, accessibility, and regulatory disclosure integration.' },
    { num: '04', title: 'Review & Launch', desc: 'Compliance review cycle, legal approval workflow, and staged rollout.' },
    { num: '05', title: 'Optimize & Scale', desc: 'A/B testing, SEO growth, and ongoing compliance monitoring.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>FINANCIAL STACK<br /><em>CONNECTED</em></>,
  stackDesc: 'CRM, portfolio, and compliance platforms integrated seamlessly.',
  stack: ['Salesforce FSC', 'Wealthbox', 'Redtail', 'Plaid', 'Stripe', 'DocuSign', 'HubSpot', 'Google Analytics 4', 'AWS', 'Auth0', 'Bloomberg', 'Morningstar'],
  faqTitle: <>Finance<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What financial services leaders ask before choosing a digital partner.',
  faqs: [
    { q: 'Do you understand FINRA and SEC marketing rules?', a: 'Yes. Our financial services team builds compliance into every asset — proper disclosures, testimonial guidelines, performance claim restrictions, and approval workflows that satisfy regulatory review.' },
    { q: 'Can you build secure client portals?', a: 'We develop encrypted client portals with MFA, role-based access, audit logging, and SOC 2-compliant hosting — suitable for wealth management, banking, and lending applications.' },
    { q: 'How do you handle financial content and YMYL SEO?', a: 'Our content team creates E-E-A-T optimized financial content with proper author credentials, fact-checking workflows, and schema markup that satisfies Google quality rater guidelines.' },
    { q: 'Do you work with FinTech startups?', a: 'Absolutely. From pre-seed landing pages to full product design and PLG websites — we help FinTech companies launch, acquire users, and prepare for fundraising.' },
    { q: 'What security standards do you follow?', a: 'SOC 2 Type II hosting, TLS 1.3 encryption, OWASP security practices, regular penetration testing, and GDPR/CCPA compliance frameworks.' },
  ],
};

export default function Finance() {
  return <IndustryInnerPage config={config} />;
}
