import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#166534',
  code: 'HC',
  label: 'Healthcare',
  canonical: '/industries/healthcare',
  metaTitle: 'Healthcare Digital Solutions | LogicWorks — HIPAA-Compliant',
  metaDescription: 'LogicWorks builds HIPAA-compliant healthcare websites, patient portals, AI scheduling, and medical SEO that fills appointment books and improves patient acquisition.',
  heroTitle: <>Healthcare<br /><span>Digital Solutions</span></>,
  heroSub: 'HIPAA-compliant websites, patient portals, AI scheduling, and healthcare SEO engineered to fill appointment books — without compromising patient trust or regulatory compliance.',
  ctaBtn: 'Get a Healthcare Audit',
  ctaNote: 'FREE HIPAA READINESS AUDIT · PATIENT ACQUISITION ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for Healthcare',
  ctaTitle: <>YOUR PRACTICE DESERVES<br /><em>DIGITAL THAT HEALS GROWTH</em>.</>,
  ctaSub: 'Book a free healthcare digital audit and see how compliant technology drives patient acquisition.',
  metrics: [
    { val: '62%', lbl: 'More Online Bookings' },
    { val: 'HIPAA', lbl: 'Compliant Builds' },
    { val: '3.1x', lbl: 'Patient Lead Volume' },
    { val: '40%', lbl: 'Front-Desk Call Reduction' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>PATIENTS SEARCH ONLINE.<br /><em>ARE YOU FOUND?</em></>,
  challengeDesc: '78% of patients research providers online before booking. Yet most practices run outdated websites, zero SEO strategy, and phone-only scheduling that loses patients to competitors with modern digital experiences.',
  checks: ['HIPAA-compliant architecture from day one', 'Online scheduling and patient portal integration', 'Medical SEO and local domination for your specialty', 'AI assistants for appointment triage and FAQ handling'],
  tags: ['HIPAA', 'Patient Portal', 'Medical SEO', 'Telehealth', 'EHR Integration'],
  outcomes: [
    { icon: '📅', title: '62% More Online Bookings', desc: 'Self-service scheduling that captures patients 24/7 without staff overhead.' },
    { icon: '🛡', title: 'Full HIPAA Compliance', desc: 'Encrypted data, BAA agreements, and audit-ready infrastructure.' },
    { icon: '🔍', title: 'Specialty SEO Dominance', desc: 'Rank for condition-specific and local provider searches.' },
    { icon: '🤖', title: 'AI Patient Assistants', desc: 'Automated triage, reminders, and pre-visit intake forms.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>DIGITAL BUILT FOR<br /><em>HEALTHCARE</em></>,
  solutionsDesc: 'Six healthcare-specific capabilities that turn your digital presence into a patient acquisition engine.',
  solutions: [
    { num: '01', title: 'HIPAA-Compliant Websites', desc: 'Secure, accessible, and conversion-optimized sites with encrypted forms, SSL, and privacy-first analytics.' },
    { num: '02', title: 'Patient Portal Development', desc: 'Self-service portals for records access, bill pay, messaging, and appointment management integrated with your EHR.' },
    { num: '03', title: 'Online Scheduling & Intake', desc: 'Real-time appointment booking, automated reminders, and digital intake forms that reduce no-shows by 35%.' },
    { num: '04', title: 'Medical SEO & Local Domination', desc: 'Condition-specific content, Google Business Profile optimization, and citation management for specialty visibility.' },
    { num: '05', title: 'Healthcare AI Assistants', desc: 'HIPAA-aware chatbots for FAQ handling, symptom triage, and appointment booking with smart human escalation.' },
    { num: '06', title: 'Reputation & Review Management', desc: 'Automated review requests, monitoring, and response workflows that build trust and improve local rankings.' },
  ],
  useCasesLabel: 'Who We Serve',
  useCasesTitle: <>HEALTHCARE<br /><em>VERTICALS</em></>,
  useCasesDesc: 'Proven digital solutions across the healthcare spectrum.',
  useCases: [
    { num: '01', title: 'Private Practices & Clinics', desc: 'Solo and group practices needing patient acquisition, online booking, and specialty SEO.' },
    { num: '02', title: 'Dental & Orthodontic', desc: 'High-converting sites with virtual consults, insurance verification, and local domination.' },
    { num: '03', title: 'Hospitals & Health Systems', desc: 'Multi-location SEO, service line marketing, and enterprise patient portal integrations.' },
    { num: '04', title: 'Telehealth & Digital Health', desc: 'Platform builds, compliance frameworks, and growth marketing for virtual care startups.' },
  ],
  processLabel: 'Process',
  processTitle: <>LIVE IN<br /><em>5 PHASES</em></>,
  processDesc: 'From compliance audit to patient acquisition — a structured healthcare digital rollout.',
  timeline: [
    { num: '01', title: 'Compliance Audit', desc: 'HIPAA readiness assessment, current site audit, and competitive landscape analysis.' },
    { num: '02', title: 'Strategy & Architecture', desc: 'Patient journey mapping, EHR integration planning, and SEO keyword strategy.' },
    { num: '03', title: 'Design & Build', desc: 'HIPAA-compliant development, portal integration, and scheduling system deployment.' },
    { num: '04', title: 'Launch & Index', desc: 'Go-live with medical schema markup, GBP optimization, and analytics tracking.' },
    { num: '05', title: 'Grow & Optimize', desc: 'Ongoing SEO, review management, and conversion optimization by specialty.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>CONNECTS TO<br /><em>YOUR SYSTEMS</em></>,
  stackDesc: 'EHR platforms, scheduling tools, and healthcare marketing stack.',
  stack: ['Epic', 'Cerner', 'Athenahealth', 'DrChrono', 'Zocdoc', 'SimplePractice', 'Tebra', 'Google Health', 'HIPAA Hosting', 'Twilio', 'Calendly', 'HL7 FHIR'],
  faqTitle: <>Healthcare<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What healthcare leaders ask before investing in digital patient acquisition.',
  faqs: [
    { q: 'Are your healthcare websites truly HIPAA compliant?', a: 'Yes. We implement encrypted data transmission, secure hosting with BAA agreements, access controls, audit logging, and privacy-compliant analytics. Compliance is architected in from discovery — not added after launch.' },
    { q: 'Can you integrate with our existing EHR system?', a: 'We integrate with Epic, Cerner, Athenahealth, DrChrono, and other major EHR platforms via HL7 FHIR APIs for scheduling, patient data sync, and portal functionality.' },
    { q: 'How long before we see more patient bookings?', a: 'Online scheduling goes live in 6–10 weeks. SEO results typically show measurable appointment increases within 3–6 months depending on specialty competition and current domain authority.' },
    { q: 'Do you handle medical content and YMYL SEO?', a: 'Yes. Our medical SEO team creates E-E-A-T optimized content with physician review workflows, medical schema markup, and condition-specific landing pages that satisfy Google quality guidelines.' },
    { q: 'Can AI assistants handle patient inquiries safely?', a: 'Our healthcare AI includes HIPAA-compliant hosting, PII redaction, guardrails that prevent medical advice, and seamless escalation to staff for clinical questions.' },
  ],
};

export default function Healthcare() {
  return <IndustryInnerPage config={config} />;
}
