import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#c8922a',
  code: 'HOS',
  label: 'Hospitality & Tourism',
  canonical: '/industries/hospitality',
  metaTitle: 'Hospitality & Tourism | LogicWorks — Direct Booking & Reputation',
  metaDescription: 'LogicWorks builds direct booking engines, reputation management, and local SEO for hotels, restaurants, and travel brands that maximize direct revenue.',
  heroTitle: <>Hospitality &<br /><span>Tourism</span></>,
  heroSub: 'Direct booking engines, reputation management, and local SEO for hotels, restaurants, and travel brands — reducing OTA commissions and filling rooms from your own channels.',
  ctaBtn: 'Get a Hospitality Audit',
  ctaNote: 'FREE BOOKING AUDIT · DIRECT REVENUE ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for Hospitality',
  ctaTitle: <>STOP PAYING OTA<br /><em>COMMISSIONS</em>.</>,
  ctaSub: 'Book a free hospitality digital audit and see how direct booking strategy increases your margins.',
  metrics: [
    { val: '38%', lbl: 'Direct Booking Increase' },
    { val: '4.8★', lbl: 'Average Review Score' },
    { val: '25%', lbl: 'OTA Commission Saved' },
    { val: '2.6x', lbl: 'Local Search Visibility' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>OTAs TAKE 15–25%<br /><em>OF YOUR REVENUE</em></>,
  challengeDesc: 'Booking.com, Expedia, and Airbnb capture guests but charge crushing commissions. Hotels and restaurants without strong direct booking channels, reputation management, and local SEO depend on OTAs for visibility — sacrificing margin on every reservation.',
  checks: ['Direct booking engine integration and optimization', 'Google Hotels and local search domination', 'Review generation and reputation management', 'Seasonal campaign strategy and yield optimization'],
  tags: ['Direct Booking', 'Google Hotels', 'Reputation', 'Local SEO', 'Revenue Management'],
  outcomes: [
    { icon: '🏨', title: '38% More Direct Bookings', desc: 'Booking engines and SEO that drive guests to your site, not OTAs.' },
    { icon: '⭐', title: '4.8★ Review Average', desc: 'Systematic review generation and response management.' },
    { icon: '💰', title: '25% Commission Saved', desc: 'Every direct booking is revenue OTAs cannot touch.' },
    { icon: '📍', title: '2.6x Local Visibility', desc: 'Dominate Google Maps, Hotels, and local travel searches.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>HOSPITALITY<br /><em>GROWTH ENGINE</em></>,
  solutionsDesc: 'Six capabilities that maximize direct revenue and guest satisfaction.',
  solutions: [
    { num: '01', title: 'Direct Booking Engine', desc: 'Commission-free reservation systems integrated with your PMS — mobile-optimized with upsell and package options.' },
    { num: '02', title: 'Hotel & Restaurant Websites', desc: 'Visual-first designs with virtual tours, menu showcases, amenity highlights, and instant booking CTAs.' },
    { num: '03', title: 'Google Hotels & Local SEO', desc: 'Google Business Profile optimization, hotel schema markup, and local search domination for destination queries.' },
    { num: '04', title: 'Reputation Management', desc: 'Automated review requests post-stay, multi-platform monitoring, and response workflows that protect your rating.' },
    { num: '05', title: 'Seasonal & Event Marketing', desc: 'Campaign strategy for peak seasons, local events, and package promotions that maximize occupancy and ADR.' },
    { num: '06', title: 'Social & Visual Content', desc: 'Instagram-worthy content strategy, user-generated content campaigns, and influencer partnerships for hospitality brands.' },
  ],
  useCasesLabel: 'Sectors',
  useCasesTitle: <>HOSPITALITY<br /><em>VERTICALS</em></>,
  useCasesDesc: 'Digital solutions across hospitality and tourism.',
  useCases: [
    { num: '01', title: 'Hotels & Resorts', desc: 'Direct booking optimization, OTA rate parity, and destination marketing for properties of all sizes.' },
    { num: '02', title: 'Restaurants & Dining', desc: 'Reservation systems, menu SEO, Google Maps domination, and review management.' },
    { num: '03', title: 'Travel & Tour Operators', desc: 'Booking platforms, itinerary marketing, and international SEO for tour companies.' },
    { num: '04', title: 'Vacation Rentals', desc: 'Direct booking sites, channel manager integration, and brand building beyond Airbnb.' },
  ],
  processLabel: 'Process',
  processTitle: <>BOOK DIRECT IN<br /><em>5 PHASES</em></>,
  processDesc: 'From OTA dependency audit to direct revenue engine — structured hospitality delivery.',
  timeline: [
    { num: '01', title: 'Revenue Audit', desc: 'OTA commission analysis, direct booking baseline, and competitive rate benchmarking.' },
    { num: '02', title: 'Strategy & Booking Setup', desc: 'Direct booking engine selection, Google Hotels integration, and rate parity planning.' },
    { num: '03', title: 'Design & Build', desc: 'Website redesign, booking flow optimization, and reputation system deployment.' },
    { num: '04', title: 'Launch & Promote', desc: 'SEO go-live, Google Hotels activation, and seasonal campaign launch.' },
    { num: '05', title: 'Fill & Optimize', desc: 'Ongoing review management, yield optimization, and direct booking incentive programs.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>HOSPITALITY STACK<br /><em>CONNECTED</em></>,
  stackDesc: 'PMS, booking engines, and reputation platforms.',
  stack: ['Cloudbeds', 'Mews', 'Opera PMS', 'Booking.com API', 'Google Hotels', 'TripAdvisor', 'TrustYou', 'Revinate', 'Mailchimp', 'Instagram API', 'Stripe', 'Channel Manager'],
  faqTitle: <>Hospitality<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What hoteliers and restaurateurs ask before investing in direct booking strategy.',
  faqs: [
    { q: 'How much can direct bookings save in OTA commissions?', a: 'OTAs typically charge 15–25% per booking. Shifting even 30% of bookings to direct saves tens of thousands annually for a mid-size property. Our average client increases direct bookings by 38% within 12 months.' },
    { q: 'Can you integrate with our property management system?', a: 'Yes. We integrate with Cloudbeds, Mews, Opera, Little Hotelier, and other PMS platforms for real-time availability, rate sync, and reservation management on your direct booking engine.' },
    { q: 'How do you improve our Google review score?', a: 'Systematic post-stay review requests via email and SMS, multi-platform monitoring, response templates, and issue escalation workflows that turn satisfied guests into 5-star reviewers.' },
    { q: 'Do you help with Google Hotels listing?', a: 'Yes. We optimize your Google Hotels free booking link, manage rate parity, implement hotel schema markup, and ensure your property appears prominently in destination searches.' },
    { q: 'Can you handle seasonal marketing campaigns?', a: 'We build seasonal campaign calendars with package promotions, event-based marketing, and dynamic pricing strategies aligned to your occupancy goals and ADR targets.' },
  ],
};

export default function Hospitality() {
  return <IndustryInnerPage config={config} />;
}
