import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#374151',
  code: 'LAW',
  label: 'Legal & Law Firms',
  canonical: '/industries/legal',
  metaTitle: 'Legal & Law Firm Marketing | LogicWorks — Attorney SEO & PPC',
  metaDescription: 'LogicWorks delivers attorney SEO, local domination, PPC, and authority websites that establish credibility and generate qualified case inquiries for law firms.',
  heroTitle: <>Legal & Law Firm<br /><span>Marketing</span></>,
  heroSub: 'Attorney SEO, local domination, PPC, and authority websites that establish credibility and generate qualified case inquiries — so your firm wins the clients that matter.',
  ctaBtn: 'Get a Legal Marketing Audit',
  ctaNote: 'FREE CASE ACQUISITION AUDIT · LOCAL SEO BENCHMARK · NO COMMITMENT',
  ctaEyebrow: 'Built for Law Firms',
  ctaTitle: <>AUTHORITY THAT<br /><em>WINS CASES</em>.</>,
  ctaSub: 'Book a free legal marketing audit and see how targeted digital strategy fills your intake pipeline.',
  metrics: [
    { val: '5.1x', lbl: 'Case Inquiry Volume' },
    { val: 'TOP3', lbl: 'Local Attorney Rankings' },
    { val: '68%', lbl: 'Cost Per Case Reduction' },
    { val: '40+', lbl: 'Practice Areas Served' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>CLIENTS GOOGLE<br /><em>THEIR CRISIS</em></>,
  challengeDesc: 'When someone needs a lawyer, they search immediately — often on mobile, often in panic. Firms without dominant local SEO, practice-area content, and fast-loading intake forms lose cases to competitors who appear first and convert fastest.',
  checks: ['Practice-area SEO that ranks for high-intent legal queries', 'Local map pack domination in your jurisdiction', 'Conversion-optimized intake forms and chat', 'Ethics-compliant advertising across all channels'],
  tags: ['Attorney SEO', 'Legal PPC', 'Intake Forms', 'Local SEO', 'Content Marketing'],
  outcomes: [
    { icon: '⚖', title: '5.1x Case Inquiries', desc: 'Practice-area pages and local SEO that capture high-intent searches.' },
    { icon: '📍', title: 'Map Pack Dominance', desc: 'Top-3 rankings for attorney near me and practice-specific queries.' },
    { icon: '💰', title: '68% Lower Cost Per Case', desc: 'Organic authority reduces dependence on expensive PPC alone.' },
    { icon: '📱', title: 'Mobile-First Intake', desc: 'One-click call, chat, and form options optimized for urgent searches.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>LEGAL MARKETING<br /><em>THAT CONVERTS</em></>,
  solutionsDesc: 'Six capabilities engineered for law firm client acquisition and authority building.',
  solutions: [
    { num: '01', title: 'Attorney SEO & Content', desc: 'Practice-area landing pages, legal blog content, and schema markup that ranks for case-winning keywords.' },
    { num: '02', title: 'Local SEO Domination', desc: 'Google Business Profile optimization, legal directory citations, and geo-targeted content for your jurisdiction.' },
    { num: '03', title: 'Legal PPC Management', desc: 'Google Ads for high-intent legal queries with ethics-compliant ad copy and landing page optimization.' },
    { num: '04', title: 'Law Firm Website Design', desc: 'Authority-building designs with attorney profiles, case results, trust badges, and mobile-first intake forms.' },
    { num: '05', title: 'Intake Optimization', desc: 'Multi-step forms, live chat, click-to-call, and CRM integration that captures leads before they call a competitor.' },
    { num: '06', title: 'Reputation Management', desc: 'Review generation, monitoring, and response strategies that build social proof and improve local rankings.' },
  ],
  useCasesLabel: 'Practice Areas',
  useCasesTitle: <>WE SERVE<br /><em>EVERY PRACTICE</em></>,
  useCasesDesc: 'Proven legal marketing across 40+ practice areas.',
  useCases: [
    { num: '01', title: 'Personal Injury', desc: 'High-competition PI SEO, PPC, and intake systems that capture accident victims fast.' },
    { num: '02', title: 'Family & Divorce Law', desc: 'Sensitive content strategy, local SEO, and conversion flows for emotional decision-makers.' },
    { num: '03', title: 'Criminal Defense', desc: 'Urgent-intent SEO and 24/7 intake optimization for time-critical searches.' },
    { num: '04', title: 'Corporate & Business Law', desc: 'Authority content, LinkedIn strategy, and B2B lead generation for business clients.' },
  ],
  processLabel: 'Process',
  processTitle: <>DOMINATE IN<br /><em>5 PHASES</em></>,
  processDesc: 'From competitive audit to case-generating machine — structured legal marketing delivery.',
  timeline: [
    { num: '01', title: 'Competitive Audit', desc: 'Analyze competitor rankings, ad spend, and intake flows in your market and practice areas.' },
    { num: '02', title: 'Keyword & Content Strategy', desc: 'Map high-intent legal queries to practice-area pages and content calendar.' },
    { num: '03', title: 'Build & Optimize', desc: 'Website redesign, intake form optimization, and CRM integration deployment.' },
    { num: '04', title: 'Launch & Rank', desc: 'SEO go-live, GBP optimization, and PPC campaign activation with ethics review.' },
    { num: '05', title: 'Cases & Scale', desc: 'Ongoing content, link building, and conversion optimization by practice area.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>LEGAL TECH<br /><em>CONNECTED</em></>,
  stackDesc: 'Case management, intake, and marketing platforms.',
  stack: ['Clio', 'MyCase', 'LawPay', 'CallRail', 'LeadDocket', 'Google Ads', 'Semrush', 'Ahrefs', 'HubSpot', 'Mailchimp', 'Avvo', 'FindLaw'],
  faqTitle: <>Legal Marketing<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What managing partners ask before investing in digital client acquisition.',
  faqs: [
    { q: 'Is your legal marketing ethics-compliant?', a: 'Yes. We follow state bar advertising rules, avoid guaranteed outcome language, include required disclaimers, and build approval workflows for all marketing assets.' },
    { q: 'How competitive is legal SEO?', a: 'Legal is one of the most competitive SEO verticals. Success requires practice-area content depth, local authority, quality backlinks, and technical excellence — our specialty for 12+ years.' },
    { q: 'How long before we see case inquiries from SEO?', a: 'Website and intake optimization shows results in 4–8 weeks. SEO typically generates measurable case inquiries within 4–8 months depending on practice area competition and domain authority.' },
    { q: 'Do you manage Google Ads for law firms?', a: 'Yes. We manage legal PPC with ethics-compliant copy, negative keyword strategies that reduce wasted spend, and landing pages optimized for case conversion — not just clicks.' },
    { q: 'Can you integrate with our case management software?', a: 'We integrate with Clio, MyCase, LeadDocket, and other legal CRMs so every intake form submission creates a matter with full source attribution.' },
  ],
};

export default function Legal() {
  return <IndustryInnerPage config={config} />;
}
