import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#1a4bdb',
  code: 'RE',
  label: 'Real Estate',
  canonical: '/industries/real-estate',
  metaTitle: 'Real Estate Digital Marketing | LogicWorks — IDX & Lead Generation',
  metaDescription: 'LogicWorks delivers IDX-integrated real estate websites, lead generation funnels, and local SEO that puts your listings in front of ready-to-buy clients.',
  heroTitle: <>Real Estate<br /><span>Digital Marketing</span></>,
  heroSub: 'IDX-integrated websites, lead generation funnels, and local SEO that puts your listings in front of buyers and sellers — before your competition does.',
  ctaBtn: 'Get a Real Estate Audit',
  ctaNote: 'FREE IDX & SEO AUDIT · LEAD FUNNEL ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for Real Estate',
  ctaTitle: <>LISTINGS THAT RANK.<br /><em>LEADS THAT CLOSE</em>.</>,
  ctaSub: 'Book a free real estate digital audit and see how IDX-powered sites drive qualified buyer and seller leads.',
  metrics: [
    { val: '4.2x', lbl: 'Lead Volume Increase' },
    { val: '89%', lbl: 'Mobile Traffic Optimized' },
    { val: 'TOP3', lbl: 'Local Map Pack Rankings' },
    { val: '35%', lbl: 'Lower Cost Per Lead' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>ZILLOW OWNS THE<br /><em>FIRST CLICK</em></>,
  challengeDesc: 'Portals capture attention but steal your leads. Agents without IDX-powered sites, local SEO dominance, and automated nurture sequences lose deals to competitors who own the digital relationship from first search to closing.',
  checks: ['MLS/IDX integration with real-time listing sync', 'Hyper-local SEO for neighborhood domination', 'Automated lead nurture and CRM integration', 'Mobile-first property search experiences'],
  tags: ['IDX/MLS', 'Local SEO', 'Lead Funnels', 'CRM Sync', 'Virtual Tours'],
  outcomes: [
    { icon: '🏠', title: '4.2x More Qualified Leads', desc: 'IDX sites that capture buyer intent before portal fatigue sets in.' },
    { icon: '📍', title: 'Map Pack Dominance', desc: 'Top-3 local rankings for neighborhood and agent searches.' },
    { icon: '📱', title: 'Mobile-First Experience', desc: '89% of home searches start on mobile — we optimize for that reality.' },
    { icon: '💰', title: '35% Lower CPL', desc: 'Organic IDX traffic reduces dependence on expensive portal leads.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>REAL ESTATE<br /><em>DIGITAL STACK</em></>,
  solutionsDesc: 'Six capabilities that turn your website into a lead-generating listing machine.',
  solutions: [
    { num: '01', title: 'IDX/MLS Integration', desc: 'Real-time listing sync, advanced search filters, map-based browsing, and saved searches that keep buyers on your site.' },
    { num: '02', title: 'Agent & Broker Websites', desc: 'Personal brand sites and brokerage platforms with lead capture, property showcases, and CRM-ready form integrations.' },
    { num: '03', title: 'Local SEO Domination', desc: 'Neighborhood landing pages, Google Business Profile optimization, and citation management for geo-targeted visibility.' },
    { num: '04', title: 'Lead Generation Funnels', desc: 'Home valuation tools, buyer guides, and seller landing pages with automated email nurture sequences.' },
    { num: '05', title: 'PPC & Retargeting', desc: 'Google Ads for high-intent property searches and retargeting campaigns that re-engage site visitors.' },
    { num: '06', title: 'Virtual Tour & Media', desc: '3D tour integration, drone photography coordination, and video marketing that makes listings stand out.' },
  ],
  useCasesLabel: 'Who We Serve',
  useCasesTitle: <>REAL ESTATE<br /><em>PROFESSIONALS</em></>,
  useCasesDesc: 'Digital solutions for every role in the property market.',
  useCases: [
    { num: '01', title: 'Individual Agents & Teams', desc: 'Personal brand sites with IDX, lead funnels, and local SEO that build your pipeline.' },
    { num: '02', title: 'Brokerages & Franchises', desc: 'Multi-agent platforms, brand consistency, and enterprise lead routing systems.' },
    { num: '03', title: 'Property Developers', desc: 'New construction marketing, pre-sale funnels, and community-specific landing pages.' },
    { num: '04', title: 'Property Management', desc: 'Rental listing sites, tenant portals, and local SEO for property management companies.' },
  ],
  processLabel: 'Process',
  processTitle: <>LIVE IN<br /><em>5 PHASES</em></>,
  processDesc: 'From MLS audit to lead-generating machine — structured real estate digital delivery.',
  timeline: [
    { num: '01', title: 'Market Audit', desc: 'Competitive analysis, MLS feed assessment, and local SEO baseline for your farm area.' },
    { num: '02', title: 'Strategy & IDX Setup', desc: 'Keyword mapping by neighborhood, IDX provider integration, and lead funnel architecture.' },
    { num: '03', title: 'Design & Build', desc: 'Mobile-first IDX site, CRM integration, and automated nurture workflow deployment.' },
    { num: '04', title: 'Launch & Rank', desc: 'Go-live with local schema markup, GBP optimization, and Google Ads activation.' },
    { num: '05', title: 'Leads & Scale', desc: 'Ongoing SEO, content marketing, and conversion optimization by market area.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>YOUR MLS &<br /><em>CRM CONNECTED</em></>,
  stackDesc: 'IDX feeds, CRMs, and real estate marketing platforms.',
  stack: ['IDX Broker', 'iHomefinder', 'Showcase IDX', 'Follow Up Boss', 'kvCORE', 'BoomTown', 'LionDesk', 'Real Geeks', 'Google Ads', 'Mailchimp', 'Zillow API', 'DocuSign'],
  faqTitle: <>Real Estate<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What agents and brokers ask before investing in real estate digital marketing.',
  faqs: [
    { q: 'Which IDX providers do you integrate with?', a: 'We integrate with IDX Broker, iHomefinder, Showcase IDX, Diverse Solutions, and most MLS-approved feed providers. We handle the technical setup and ensure compliance with your board rules.' },
    { q: 'How is this different from using Zillow or Realtor.com?', a: 'Portals rent you visibility — we build you an asset. Your IDX site captures leads directly, builds your email list, and ranks in Google for local searches portals cannot control.' },
    { q: 'How long until I see leads from SEO?', a: 'IDX sites go live in 4–8 weeks. Local SEO typically generates measurable organic leads within 3–5 months, with compounding returns as neighborhood pages rank.' },
    { q: 'Can you integrate with my CRM?', a: 'Yes — Follow Up Boss, kvCORE, BoomTown, LionDesk, Salesforce, and HubSpot integrations are standard. Every form submission routes to your CRM with lead source tracking.' },
    { q: 'Do you work with specific farm areas or cities?', a: 'We build hyper-local SEO strategies around your farm area — neighborhood landing pages, local content, and geo-targeted ads that dominate your specific market.' },
  ],
};

export default function RealEstate() {
  return <IndustryInnerPage config={config} />;
}
