import { IndustryInnerPage, type IndustryPageConfig } from './shared';

const config: IndustryPageConfig = {
  accent: '#0891b2',
  code: 'SaaS',
  label: 'SaaS & Technology',
  canonical: '/industries/saas',
  metaTitle: 'SaaS & Technology | LogicWorks — Product-Led Growth & B2B SEO',
  metaDescription: 'LogicWorks builds product-led growth websites, developer-first SEO, and B2B demand generation for SaaS and technology companies at every stage.',
  heroTitle: <>SaaS &<br /><span>Technology</span></>,
  heroSub: 'Product-led growth websites, developer-first SEO, and B2B demand generation for tech companies — from seed-stage startups to enterprise platforms scaling past $10M ARR.',
  ctaBtn: 'Get a SaaS Growth Audit',
  ctaNote: 'FREE PLG AUDIT · PIPELINE ROADMAP · NO COMMITMENT',
  ctaEyebrow: 'Built for SaaS',
  ctaTitle: <>PIPELINE IS NOT A<br /><em>MARKETING PROBLEM ALONE</em>.</>,
  ctaSub: 'Book a free SaaS growth audit and see where your website leaks trials, demos, and revenue.',
  metrics: [
    { val: '3.6x', lbl: 'Trial Sign-Up Rate' },
    { val: '58%', lbl: 'Demo Request Lift' },
    { val: '2.1x', lbl: 'Organic Pipeline Growth' },
    { val: '40%', lbl: 'CAC Reduction' },
  ],
  challengeLabel: 'The Challenge',
  challengeTitle: <>YOUR WEBSITE IS<br /><em>YOUR TOP SALESPERSON</em></>,
  challengeDesc: 'In SaaS, 70% of the buyer journey happens before sales speaks to a prospect. Weak positioning, slow sites, and feature-list pages instead of outcome-driven narratives kill conversion. PLG companies live or die by their digital experience.',
  checks: ['Product-led growth website architecture', 'Developer documentation and technical SEO', 'Comparison and alternative page strategies', 'Full-funnel analytics from visit to activation'],
  tags: ['PLG', 'B2B SEO', 'Developer Docs', 'HubSpot', 'Product Marketing'],
  outcomes: [
    { icon: '🚀', title: '3.6x Trial Sign-Ups', desc: 'PLG-optimized flows that reduce friction from landing to activation.' },
    { icon: '📞', title: '58% More Demos', desc: 'Enterprise pages and CTAs that convert high-intent evaluators.' },
    { icon: '📈', title: '2.1x Organic Pipeline', desc: 'Bottom-funnel SEO that captures comparison and alternative searches.' },
    { icon: '💰', title: '40% Lower CAC', desc: 'Organic and PLG channels reduce paid acquisition dependence.' },
  ],
  solutionsLabel: 'Solutions',
  solutionsTitle: <>SAAS GROWTH<br /><em>PLAYBOOK</em></>,
  solutionsDesc: 'Six capabilities that drive pipeline from first visit to paid conversion.',
  solutions: [
    { num: '01', title: 'PLG Website Architecture', desc: 'Self-serve trial flows, interactive demos, and onboarding paths that convert visitors to activated users without sales friction.' },
    { num: '02', title: 'B2B SEO & Content Engine', desc: 'Bottom-funnel keyword targeting, comparison pages, integration docs, and thought leadership that captures evaluators.' },
    { num: '03', title: 'Developer Documentation SEO', desc: 'Technical documentation optimized for developer search — API references, tutorials, and integration guides that drive adoption.' },
    { num: '04', title: 'Product Marketing Pages', desc: 'Feature pages reframed as outcome narratives with social proof, ROI calculators, and competitive differentiation.' },
    { num: '05', title: 'Demand Generation Campaigns', desc: 'LinkedIn Ads, Google Ads, and retargeting with account-based targeting for enterprise pipeline.' },
    { num: '06', title: 'Analytics & Attribution', desc: 'Full-funnel tracking from first touch to revenue with product analytics integration and cohort reporting.' },
  ],
  useCasesLabel: 'SaaS Stages',
  useCasesTitle: <>EVERY STAGE<br /><em>OF GROWTH</em></>,
  useCasesDesc: 'Digital solutions calibrated to your SaaS maturity.',
  useCases: [
    { num: '01', title: 'Pre-Seed & Seed Startups', desc: 'Investor-ready websites, MVP positioning, and launch marketing for product-market fit validation.' },
    { num: '02', title: 'Series A–B Growth', desc: 'PLG optimization, SEO engine buildout, and demand gen scaling for repeatable pipeline.' },
    { num: '03', title: 'Enterprise SaaS', desc: 'ABM campaigns, enterprise landing pages, and security/compliance trust centers.' },
    { num: '04', title: 'Developer Tools & API', desc: 'Documentation sites, developer community SEO, and open-source growth strategies.' },
  ],
  processLabel: 'Process',
  processTitle: <>GROW IN<br /><em>5 PHASES</em></>,
  processDesc: 'From growth audit to pipeline engine — structured SaaS digital delivery.',
  timeline: [
    { num: '01', title: 'Growth Audit', desc: 'Funnel analysis, competitive positioning review, and SEO/content gap assessment.' },
    { num: '02', title: 'Strategy & Positioning', desc: 'ICP refinement, messaging architecture, and channel priority matrix.' },
    { num: '03', title: 'Build & Optimize', desc: 'Website redesign, PLG flow optimization, and content engine launch.' },
    { num: '04', title: 'Launch & Activate', desc: 'SEO go-live, paid campaign activation, and analytics instrumentation.' },
    { num: '05', title: 'Scale & Iterate', desc: 'Continuous CRO, content scaling, and channel expansion based on cohort data.' },
  ],
  stackLabel: 'Integrations',
  stackTitle: <>SAAS STACK<br /><em>CONNECTED</em></>,
  stackDesc: 'Product, marketing, and analytics platforms.',
  stack: ['HubSpot', 'Salesforce', 'Segment', 'Amplitude', 'Mixpanel', 'Stripe', 'Intercom', 'Clearbit', 'Mutiny', 'Webflow', 'Contentful', 'Google Analytics 4'],
  faqTitle: <>SaaS<br /><em>QUESTIONS ANSWERED</em></>,
  faqDesc: 'What SaaS founders and CMOs ask before investing in growth.',
  faqs: [
    { q: 'Do you understand product-led growth vs sales-led?', a: 'Yes. We build PLG experiences with self-serve trials, freemium conversion paths, and product-qualified lead scoring — as well as enterprise SLG pages with demo request optimization and ABM campaigns.' },
    { q: 'Can you help with comparison and alternative pages?', a: 'Bottom-funnel comparison pages are our specialty — "[Your Product] vs [Competitor]" and "[Competitor] alternative" pages that capture high-intent evaluators and rank for commercial keywords.' },
    { q: 'How do you measure SaaS marketing success?', a: 'We track metrics that matter — trial sign-ups, activation rate, PQL volume, demo requests, pipeline influenced, CAC, and LTV:CAC ratio — not vanity traffic numbers.' },
    { q: 'Do you work with early-stage startups?', a: 'Yes. From pre-seed landing pages to Series B growth engines — we scale our engagement to your stage, budget, and growth priorities.' },
    { q: 'Can you optimize our developer documentation for SEO?', a: 'We optimize docs for developer search intent — API references, tutorial content, and integration guides that drive organic adoption and reduce support burden.' },
  ],
};

export default function Saas() {
  return <IndustryInnerPage config={config} />;
}
